"""tabla publicacion

Revision ID: 5dd752863e15
Revises: aa639452b53f
Create Date: 2025-05-13 16:32:14.293914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd752863e15'
down_revision = 'aa639452b53f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publicaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profesion', sa.String(length=100), nullable=False),
    sa.Column('contenido', sa.String(length=300), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('email_contacto', sa.String(length=150), nullable=False),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publicaciones')
    # ### end Alembic commands ###
